TOOLS = {
    "core_tools": [
        "JSA Generator",
        "PTW Manager",
        "Risk Analyzer",
        "Incident Reporter",
        "Inspection Suite",
        "Training Manager",
        "Audit System",
        "Compliance Checker",
    ],
    "ai_tools": [
        "AI Chat",
        "AI Builder",
        "AI Fixer",
        "AI Analyzer",
        "AI Planner",
        "AI Debugger",
        "AI Reviewer",
        "AI Predictor",
    ],
    "system_tools": [
        "Logs Viewer",
        "Health Monitor",
        "System Status",
        "Engine Control",
        "Task Queue",
        "Worker Monitor",
        "Execution Pipeline",
        "Auto Fix Engine",
    ],
    "data_tools": [
        "Upload Manager",
        "Document Parser",
        "Data Viewer",
        "Storage Manager",
        "Memory System",
        "Vector DB",
        "Search Engine",
        "Export System",
    ],
    "admin_tools": [
        "User Manager",
        "Roles & Permissions",
        "Billing",
        "Subscriptions",
        "API Keys",
        "Security Panel",
        "Access Control",
        "Settings",
    ],
}
