"""Advanced Export — HTML, Markdown, TXT, JSON, ZIP (batch) export formats."""

from __future__ import annotations

import json
import os
import tempfile
import uuid
import zipfile
from datetime import datetime, timezone
from pathlib import Path

_EXPORT_DIR = os.path.join(tempfile.gettempdir(), "docgen_exports")
os.makedirs(_EXPORT_DIR, exist_ok=True)


def _unique_path(ext: str) -> str:
    return os.path.join(_EXPORT_DIR, f"{uuid.uuid4().hex}.{ext}")


# ---------------------------------------------------------------------------
# HTML export
# ---------------------------------------------------------------------------

def export_html(title: str, sections: list[dict]) -> str:
    path = _unique_path("html")
    html_sections = ""
    for sec in sections:
        lines_html = ""
        for line in sec["content"].splitlines():
            t = line.strip()
            if not t:
                lines_html += "<br>\n"
            elif t.startswith(("•", "-", "*")):
                lines_html += f"  <li>{t.lstrip('•-* ')}</li>\n"
            elif "|" in t and not t.replace("|", "").replace("-", "").replace(" ", ""):
                pass  # skip separator rows
            elif "|" in t:
                cells = [c.strip() for c in t.split("|") if c.strip()]
                row_html = "".join(f"<td>{c}</td>" for c in cells)
                lines_html += f"<tr>{row_html}</tr>\n"
            else:
                lines_html += f"<p>{t}</p>\n"
        has_table = "|" in sec["content"]
        content_html = (
            f"<table class='data-table'>\n{lines_html}</table>"
            if has_table
            else f"<ul>\n{lines_html}</ul>" if "<li>" in lines_html
            else lines_html
        )
        html_sections += f"""
    <section class="doc-section">
      <h2>{sec['heading']}</h2>
      {content_html}
    </section>"""

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{title}</title>
  <style>
    body {{ font-family: 'Segoe UI', Arial, sans-serif; max-width: 900px; margin: 0 auto;
            padding: 40px 24px; color: #1a1a2e; line-height: 1.7; }}
    h1   {{ color: #1a1a7a; border-bottom: 3px solid #007b8a; padding-bottom: 12px; }}
    h2   {{ color: #007b8a; margin-top: 32px; font-size: 1.2rem; }}
    p    {{ margin: 6px 0; }}
    ul   {{ padding-left: 20px; }}
    li   {{ margin: 4px 0; }}
    .data-table {{ border-collapse: collapse; width: 100%; margin: 12px 0; }}
    .data-table td {{ border: 1px solid #ccc; padding: 8px 12px; }}
    .data-table tr:first-child td {{ background: #1a1a7a; color: white; font-weight: bold; }}
    .data-table tr:nth-child(even) td {{ background: #eaf4f4; }}
    .meta {{ font-size: 0.8rem; color: #888; margin-top: 40px; border-top: 1px solid #eee;
             padding-top: 12px; }}
    @media print {{ body {{ max-width: 100%; }} }}
  </style>
</head>
<body>
  <h1>{title}</h1>
  {html_sections}
  <div class="meta">Generated by Easy AI · {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}</div>
</body>
</html>"""
    with open(path, "w", encoding="utf-8") as f:
        f.write(html)
    return path


# ---------------------------------------------------------------------------
# Markdown export
# ---------------------------------------------------------------------------

def export_markdown(title: str, sections: list[dict]) -> str:
    path = _unique_path("md")
    lines = [f"# {title}\n", f"> Generated by Easy AI · {datetime.now(timezone.utc).strftime('%Y-%m-%d')}\n"]
    for sec in sections:
        lines.append(f"\n## {sec['heading']}\n")
        for line in sec["content"].splitlines():
            t = line.strip()
            if not t:
                lines.append("")
            elif t.startswith(("•", "- ", "* ")):
                lines.append(f"- {t.lstrip('•-* ')}")
            elif "|" in t:
                lines.append(t)
            else:
                lines.append(t)
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    return path


# ---------------------------------------------------------------------------
# Plain text export
# ---------------------------------------------------------------------------

def export_txt(title: str, sections: list[dict]) -> str:
    path = _unique_path("txt")
    lines = [title, "=" * len(title), ""]
    for sec in sections:
        lines += [sec["heading"], "-" * len(sec["heading"]), sec["content"], ""]
    lines += [f"\nGenerated by Easy AI — {datetime.now(timezone.utc).strftime('%Y-%m-%d')}"]
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    return path


# ---------------------------------------------------------------------------
# JSON export
# ---------------------------------------------------------------------------

def export_json(title: str, sections: list[dict], meta: dict | None = None) -> str:
    path = _unique_path("json")
    payload = {
        "title":      title,
        "sections":   sections,
        "generated":  datetime.now(timezone.utc).isoformat(),
        "generator":  "Easy AI",
        "meta":       meta or {},
    }
    with open(path, "w", encoding="utf-8") as f:
        json.dump(payload, f, indent=2, ensure_ascii=False)
    return path


# ---------------------------------------------------------------------------
# Batch ZIP export
# ---------------------------------------------------------------------------

def export_zip(documents: list[dict]) -> str:
    """Bundle multiple exported files into a single ZIP archive.

    Each item in documents must have: title, sections, and optionally
    pdf_path, docx_path, pptx_path, xlsx_path.
    """
    zip_path = _unique_path("zip")
    with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zf:
        for i, doc in enumerate(documents, start=1):
            title    = doc.get("title", f"Document {i}")
            sections = doc.get("sections", [])
            safe_name = "".join(c if c.isalnum() or c in " -_" else "_" for c in title)[:40]

            # Always include TXT + HTML in the bundle
            txt_path  = export_txt(title, sections)
            html_path = export_html(title, sections)
            zf.write(txt_path,  arcname=f"{i:02d}_{safe_name}.txt")
            zf.write(html_path, arcname=f"{i:02d}_{safe_name}.html")

            # Include any pre-generated binary files
            for ext in ("pdf_path", "docx_path", "pptx_path", "xlsx_path"):
                fpath = doc.get(ext)
                if fpath and os.path.isfile(fpath):
                    suffix = Path(fpath).suffix
                    zf.write(fpath, arcname=f"{i:02d}_{safe_name}{suffix}")
    return zip_path
