"""Export utilities – convert structured content to PDF, DOCX, PPTX and XLSX."""

from __future__ import annotations

import os
import tempfile
import uuid

from docx import Document as DocxDocument
from docx.shared import Pt, RGBColor
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer


_EXPORT_DIR = os.path.join(tempfile.gettempdir(), "docgen_exports")
os.makedirs(_EXPORT_DIR, exist_ok=True)


def _unique_path(ext: str) -> str:
    return os.path.join(_EXPORT_DIR, f"{uuid.uuid4().hex}.{ext}")


# ---------------------------------------------------------------------------
# PDF
# ---------------------------------------------------------------------------

def export_pdf(title: str, sections: list[dict]) -> str:
    path = _unique_path("pdf")
    doc = SimpleDocTemplate(
        path,
        pagesize=A4,
        leftMargin=2 * cm,
        rightMargin=2 * cm,
        topMargin=2 * cm,
        bottomMargin=2 * cm,
    )
    styles = getSampleStyleSheet()

    title_style = ParagraphStyle(
        "DocTitle",
        parent=styles["Title"],
        fontSize=20,
        spaceAfter=18,
        textColor=(0.1, 0.1, 0.5),
    )
    heading_style = ParagraphStyle(
        "DocHeading",
        parent=styles["Heading2"],
        fontSize=13,
        spaceBefore=14,
        spaceAfter=6,
        textColor=(0.15, 0.15, 0.4),
    )
    body_style = ParagraphStyle(
        "DocBody",
        parent=styles["Normal"],
        fontSize=10,
        leading=15,
        spaceAfter=6,
    )

    story = [Paragraph(title, title_style)]

    for sec in sections:
        story.append(Paragraph(sec["heading"], heading_style))
        for line in sec["content"].splitlines():
            line = line.strip()
            if line:
                story.append(Paragraph(line, body_style))
        story.append(Spacer(1, 0.3 * cm))

    doc.build(story)
    return path


# ---------------------------------------------------------------------------
# DOCX
# ---------------------------------------------------------------------------

def export_docx(title: str, sections: list[dict]) -> str:
    path = _unique_path("docx")
    doc = DocxDocument()

    # Title
    title_para = doc.add_heading(title, level=0)
    title_para.runs[0].font.color.rgb = RGBColor(0x1A, 0x1A, 0x7A)

    for sec in sections:
        h = doc.add_heading(sec["heading"], level=1)
        h.runs[0].font.color.rgb = RGBColor(0x26, 0x26, 0x66)
        for line in sec["content"].splitlines():
            if line.strip():
                p = doc.add_paragraph(line.strip())
                p.runs[0].font.size = Pt(11)

        doc.add_paragraph("")  # spacing

    doc.save(path)
    return path


# ---------------------------------------------------------------------------
# PPTX
# ---------------------------------------------------------------------------

def export_pptx(title: str, sections: list[dict]) -> str:
    from pptx import Presentation
    from pptx.util import Inches, Pt as PptPt

    path = _unique_path("pptx")
    prs = Presentation()

    # Title slide
    title_layout = prs.slide_layouts[0]
    slide = prs.slides.add_slide(title_layout)
    slide.shapes.title.text = title
    if slide.placeholders[1].has_text_frame:
        slide.placeholders[1].text = "Generated by Easy AI"

    # One slide per section
    content_layout = prs.slide_layouts[1]
    for sec in sections:
        slide = prs.slides.add_slide(content_layout)
        slide.shapes.title.text = sec["heading"]
        body_tf = slide.placeholders[1].text_frame
        body_tf.word_wrap = True
        # Use paragraphs to avoid very long single run
        first = True
        for line in sec["content"].splitlines():
            line = line.strip()
            if not line:
                continue
            if first:
                body_tf.paragraphs[0].text = line
                first = False
            else:
                p = body_tf.add_paragraph()
                p.text = line

    prs.save(path)
    return path


# ---------------------------------------------------------------------------
# XLSX
# ---------------------------------------------------------------------------

def export_xlsx(title: str, sections: list[dict]) -> str:
    from openpyxl import Workbook
    from openpyxl.styles import Font

    path = _unique_path("xlsx")
    wb = Workbook()
    ws = wb.active
    ws.title = "Generated Data"

    # Title row
    ws.append([title])
    ws["A1"].font = Font(bold=True, size=14)
    ws.append([])  # blank row

    for sec in sections:
        ws.append([sec["heading"]])
        ws.cell(row=ws.max_row, column=1).font = Font(bold=True)
        for line in sec["content"].splitlines():
            line = line.strip()
            if line:
                ws.append([line])
        ws.append([])  # blank row between sections

    # Auto-fit column width (approximate)
    for col in ws.columns:
        max_len = max((len(str(cell.value)) if cell.value else 0) for cell in col)
        ws.column_dimensions[col[0].column_letter].width = min(max_len + 4, 100)

    wb.save(path)
    return path
