"""
ORD AI — HybridRAG
Hybrid retrieval: BM25 keyword search + optional vector similarity.
Works with zero external dependencies (BM25 only).
With sentence-transformers + numpy installed: adds semantic search.
"""
import re
import math
import json
import sqlite3
import threading
import time
from collections import Counter
from typing import Optional

DB_PATH = "/tmp/ord_ai_rag.db"

# ── Try to import optional vector search deps ─────────────────────────
try:
    import numpy as np
    from sentence_transformers import SentenceTransformer
    _ST_MODEL = SentenceTransformer("all-MiniLM-L6-v2")
    _VECTOR_OK = True
except Exception:
    _VECTOR_OK = False
    np = None


def _db():
    con = sqlite3.connect(DB_PATH, check_same_thread=False)
    con.row_factory = sqlite3.Row
    return con


def _init_db():
    con = _db()
    con.executescript("""
        CREATE TABLE IF NOT EXISTS documents (
            id        INTEGER PRIMARY KEY AUTOINCREMENT,
            title     TEXT NOT NULL,
            content   TEXT NOT NULL,
            source    TEXT DEFAULT '',
            tags      TEXT DEFAULT '',
            embedding BLOB,
            ts        REAL NOT NULL
        );
        CREATE VIRTUAL TABLE IF NOT EXISTS docs_fts
            USING fts5(title, content, tags, content=documents, content_rowid=id);
        CREATE TABLE IF NOT EXISTS doc_graph (
            src_id  INTEGER NOT NULL,
            dst_id  INTEGER NOT NULL,
            PRIMARY KEY(src_id, dst_id)
        );
    """)
    con.commit()
    con.close()


_init_db()

_DEFAULT_DOCS = [
    ("ORD AI Overview",
     "ORD AI is an infinite-loop human-AI factory with 50 Cores, 50 Engines, and 50 AI Builders. "
     "All 4 blueprints unified: ∞-Loop Factory, AI Pilot, Three-Window IDE, SpecKit Autopilot.",
     "system", "overview,ai,platform"),
    ("Agent Pipeline",
     "5-agent pipeline: Planner (task DAG), Implementer (code generation), Validator (test suite), "
     "Reviewer (code review + HITL routing), Merger (CI/CD + PR creation). Each agent can call "
     "external LLMs via the ModelRouter.",
     "system", "agents,pipeline"),
    ("Model Router",
     "MultiModelRouter supports LMStudio, Ollama, OpenAI-compatible backends. Dynamic routing by "
     "task type: code_generation→lmstudio, review→openai, fast_iteration→ollama. Falls back to "
     "built-in mock when all backends offline.",
     "system", "models,router"),
    ("Memory System",
     "Three-tier memory: Short-term (in-process TTL cache, 1hr), Long-term (SQLite FTS, permanent), "
     "Episodic (event log with kind/payload, queryable). Used for cross-session learning and "
     "bug pattern recognition.",
     "system", "memory,learning"),
    ("HITL Policy",
     "Human-in-the-Loop lanes: REQUIRED (core/auth/deployment), OPTIONAL (tools/docs, auto-approved after 24h), "
     "NONE (tests/scripts, fully autonomous). Cost controls: $50/day budget, 4096 max tokens/task.",
     "system", "hitl,policy,safety"),
    ("RAG System",
     "Hybrid retrieval: BM25 keyword search (always available) + semantic vector search (with "
     "sentence-transformers). Supports ingest of build artifacts, docs, code. Used by agents "
     "to fetch relevant context before generating responses.",
     "system", "rag,retrieval,search"),
    ("Fine-tuning Engine",
     "LoRA/QLoRA fine-tuning on build history. Base model: llama-3.1-8b or any GGUF. "
     "Training data auto-generated from successful builds. Export to GGUF/ONNX for edge deployment. "
     "Results in permanent learning, not just in-context.",
     "system", "finetune,learning,lora"),
    ("Deployment",
     "Docker + docker-compose for local. Kubernetes manifests for production. "
     "GitHub Actions CI/CD pipeline. Supports AWS ECS, GCP Cloud Run, Azure ACI. "
     "All configs generated by the Merger agent.",
     "system", "deploy,docker,kubernetes"),
]


class HybridRAG:
    """Hybrid retrieval system: BM25 + optional vector search."""

    _instance = None
    _lock = threading.Lock()

    def __init__(self):
        self._seed_defaults()

    @classmethod
    def get_instance(cls) -> "HybridRAG":
        with cls._lock:
            if cls._instance is None:
                cls._instance = cls()
        return cls._instance

    def _seed_defaults(self):
        con = _db()
        cur = con.cursor()
        cur.execute("SELECT COUNT(*) as cnt FROM documents")
        if cur.fetchone()["cnt"] == 0:
            for title, content, source, tags in _DEFAULT_DOCS:
                self._ingest_raw(title, content, source, tags)
        con.close()

    def _tokenize(self, text: str) -> list[str]:
        return re.findall(r"\w+", text.lower())

    def _bm25_score(self, query_tokens: list[str], doc_tokens: list[str],
                    avg_dl: float, k1: float = 1.5, b: float = 0.75) -> float:
        tf = Counter(doc_tokens)
        dl = len(doc_tokens)
        score = 0.0
        for term in query_tokens:
            if term not in tf:
                continue
            idf = math.log(1 + 1)  # simplified (no corpus-level DF)
            freq = tf[term]
            score += idf * (freq * (k1 + 1)) / (freq + k1 * (1 - b + b * dl / max(avg_dl, 1)))
        return score

    def _ingest_raw(self, title: str, content: str, source: str = "", tags: str = "") -> int:
        embedding = None
        if _VECTOR_OK:
            try:
                vec = _ST_MODEL.encode(f"{title} {content}")
                embedding = vec.tobytes()
            except Exception:
                pass
        con = _db()
        cur = con.cursor()
        cur.execute(
            "INSERT INTO documents (title, content, source, tags, embedding, ts) VALUES (?,?,?,?,?,?)",
            (title, content, source, tags, embedding, time.time()),
        )
        row_id = cur.lastrowid
        cur.execute(
            "INSERT INTO docs_fts(rowid, title, content, tags) VALUES (?,?,?,?)",
            (row_id, title, content, tags),
        )
        con.commit()
        con.close()
        return row_id

    def ingest(self, title: str, content: str, source: str = "", tags: str = "") -> dict:
        """Add a document to the knowledge base."""
        doc_id = self._ingest_raw(title, content, source, tags)
        return {"id": doc_id, "title": title, "source": source, "vector_indexed": _VECTOR_OK}

    def query(self, q: str, top_k: int = 5, mode: str = "hybrid") -> dict:
        """Query the knowledge base. mode: bm25 | vector | hybrid"""
        results = []

        # ── BM25 retrieval ────────────────────────────────────────────
        if mode in ("bm25", "hybrid"):
            con = _db()
            cur = con.cursor()
            try:
                cur.execute(
                    "SELECT d.id, d.title, d.content, d.source, d.tags "
                    "FROM docs_fts f JOIN documents d ON d.id = f.rowid "
                    "WHERE docs_fts MATCH ? ORDER BY rank LIMIT ?",
                    (q, top_k * 2),
                )
                rows = [dict(r) for r in cur.fetchall()]
            except sqlite3.OperationalError:
                cur.execute(
                    "SELECT id, title, content, source, tags FROM documents "
                    "WHERE content LIKE ? OR title LIKE ? LIMIT ?",
                    (f"%{q}%", f"%{q}%", top_k * 2),
                )
                rows = [dict(r) for r in cur.fetchall()]
            con.close()
            q_tokens = self._tokenize(q)
            avg_dl = sum(len(self._tokenize(r["content"])) for r in rows) / max(len(rows), 1)
            for r in rows:
                score = self._bm25_score(q_tokens, self._tokenize(r["content"] + " " + r["title"]), avg_dl)
                r["score"] = score
                r["method"] = "bm25"
                results.append(r)

        # ── Vector retrieval ──────────────────────────────────────────
        if mode in ("vector", "hybrid") and _VECTOR_OK:
            try:
                q_vec = _ST_MODEL.encode(q)
                con = _db()
                cur = con.cursor()
                cur.execute("SELECT id, title, content, source, tags, embedding FROM documents WHERE embedding IS NOT NULL")
                for row in cur.fetchall():
                    doc_vec = np.frombuffer(row["embedding"], dtype=np.float32)
                    sim = float(np.dot(q_vec, doc_vec) / (np.linalg.norm(q_vec) * np.linalg.norm(doc_vec) + 1e-9))
                    existing = next((r for r in results if r["id"] == row["id"]), None)
                    if existing:
                        existing["score"] = max(existing["score"], sim)
                        existing["method"] = "hybrid"
                    else:
                        results.append({
                            "id": row["id"], "title": row["title"],
                            "content": row["content"], "source": row["source"],
                            "tags": row["tags"], "score": sim, "method": "vector",
                        })
                con.close()
            except Exception:
                pass

        results.sort(key=lambda r: r.get("score", 0), reverse=True)
        results = results[:top_k]

        # Build context string for agent consumption
        context = "\n\n".join(
            f"[{r['title']}]\n{r['content'][:400]}" for r in results
        )

        return {
            "query": q,
            "results": results,
            "context": context,
            "mode": mode,
            "vector_search": _VECTOR_OK,
            "total_found": len(results),
        }

    def stats(self) -> dict:
        con = _db()
        cur = con.cursor()
        cur.execute("SELECT COUNT(*) as cnt FROM documents")
        total = cur.fetchone()["cnt"]
        cur.execute("SELECT COUNT(*) as cnt FROM documents WHERE embedding IS NOT NULL")
        vectorized = cur.fetchone()["cnt"]
        cur.execute("SELECT source, COUNT(*) as cnt FROM documents GROUP BY source")
        by_source = {r["source"]: r["cnt"] for r in cur.fetchall()}
        cur.execute("SELECT COUNT(*) as cnt FROM doc_graph")
        edges = cur.fetchone()["cnt"]
        con.close()
        return {
            "total_documents": total,
            "vectorized": vectorized,
            "vector_search_enabled": _VECTOR_OK,
            "graph_edges": edges,
            "by_source": by_source,
        }

    def add_relationship(self, doc_id_1: int, doc_id_2: int) -> None:
        """Add a knowledge graph edge between two documents."""
        con = _db()
        try:
            con.execute(
                "INSERT OR IGNORE INTO doc_graph (src_id, dst_id) VALUES (?,?)", (doc_id_1, doc_id_2)
            )
            con.execute(
                "INSERT OR IGNORE INTO doc_graph (src_id, dst_id) VALUES (?,?)", (doc_id_2, doc_id_1)
            )
            con.commit()
        except Exception:
            pass
        con.close()

    def _graph_expand(self, seed_ids: list[int], depth: int = 1) -> list[dict]:
        """Traverse knowledge graph edges to find related documents."""
        if not seed_ids:
            return []
        con = _db()
        cur = con.cursor()
        visited = set(seed_ids)
        frontier = list(seed_ids)
        extra: list[dict] = []
        for _ in range(depth):
            if not frontier:
                break
            placeholders = ",".join("?" for _ in frontier)
            cur.execute(
                f"SELECT dst_id FROM doc_graph WHERE src_id IN ({placeholders})", frontier
            )
            neighbors = [r[0] for r in cur.fetchall() if r[0] not in visited]
            if not neighbors:
                break
            visited.update(neighbors)
            frontier = neighbors
            np_holders = ",".join("?" for _ in neighbors)
            cur.execute(
                f"SELECT id, title, content, source, tags FROM documents WHERE id IN ({np_holders})",
                neighbors,
            )
            for row in cur.fetchall():
                extra.append(dict(row))
        con.close()
        return extra
