import os

class ProjectBuilder:
    def build_project(self, task):
        # Example: create folders/files for backend, frontend, db
        base = 'output_project'
        os.makedirs(base, exist_ok=True)
        for part in task.get('plan', []):
            part_dir = os.path.join(base, part.replace(' ', '_').lower())
            os.makedirs(part_dir, exist_ok=True)
            with open(os.path.join(part_dir, 'README.md'), 'w') as f:
                f.write(f"# {part}\nGenerated by ODEX Engine.")
        return f"Created structure in {base}"






