"""
Presentation Engine — Generates PPTX slide decks.
"""
import os
from datetime import datetime
from pptx import Presentation
from pptx.util import Inches, Pt, Emu
from pptx.dml.color import RGBColor
from pptx.enum.text import PP_ALIGN

DOWNLOAD_DIR = os.path.join(os.path.dirname(os.path.dirname(__file__)), "downloads")
os.makedirs(DOWNLOAD_DIR, exist_ok=True)

BRAND_BLUE = RGBColor(0x25, 0x63, 0xEB)
DARK_BLUE = RGBColor(0x1E, 0x40, 0xAF)
GRAY = RGBColor(0x6B, 0x72, 0x80)
WHITE = RGBColor(0xFF, 0xFF, 0xFF)
DARK = RGBColor(0x1F, 0x29, 0x37)


def generate_slide_content(prompt: str) -> list:
    title = prompt[:60].strip().title()
    return [
        {"title": title, "subtitle": "Generated by EASY AI DOC & EDUCATION CORE", "type": "title"},
        {
            "title": "Agenda",
            "bullets": ["Introduction & Overview", "Background Research", "Key Analysis & Findings",
                        "Data & Metrics", "Strategic Recommendations", "Implementation Plan",
                        "Timeline & Milestones", "Q&A"],
            "type": "content",
        },
        {
            "title": "Introduction",
            "bullets": [f"Topic: {prompt[:80]}", "Scope: Comprehensive analysis and recommendations",
                        "Methodology: Data-driven approach with industry benchmarks",
                        "Goal: Actionable insights for decision-making"],
            "type": "content",
        },
        {
            "title": "Background & Context",
            "bullets": ["Industry landscape and current trends", "Historical performance analysis",
                        "Competitive environment assessment", "Stakeholder requirements mapping"],
            "type": "content",
        },
        {
            "title": "Key Findings",
            "bullets": ["Finding 1: Primary objectives achievable within scope",
                        "Finding 2: Resource allocation aligns with benchmarks",
                        "Finding 3: Timeline is realistic with proper management",
                        "Finding 4: Risks identified and mitigation planned"],
            "type": "content",
        },
        {
            "title": "Data & Metrics",
            "bullets": ["Performance: 95% target achievement rate",
                        "Efficiency: 40% improvement in processing",
                        "Quality: 98% accuracy in deliverables",
                        "Satisfaction: 4.8/5.0 stakeholder rating"],
            "type": "content",
        },
        {
            "title": "Recommendations",
            "bullets": ["Phase 1: Immediate improvements (0-30 days)",
                        "Phase 2: Process optimization (30-90 days)",
                        "Phase 3: Strategic enhancements (90-180 days)",
                        "Phase 4: Full transformation (180-365 days)"],
            "type": "content",
        },
        {
            "title": "Implementation Timeline",
            "bullets": ["Week 1-4: Foundation and setup",
                        "Week 5-8: Core development and testing",
                        "Week 9-12: Integration and validation",
                        "Week 13-16: Launch and monitoring"],
            "type": "content",
        },
        {
            "title": "Next Steps",
            "bullets": ["Approve proposed plan and budget", "Assemble project team",
                        "Begin Phase 1 implementation", "Schedule first review checkpoint"],
            "type": "content",
        },
        {"title": "Thank You", "subtitle": f"Questions?\n\nGenerated on {datetime.now().strftime('%B %d, %Y')}", "type": "title"},
    ]


def _add_bg(slide, color=DARK_BLUE):
    bg = slide.background
    fill = bg.fill
    fill.solid()
    fill.fore_color.rgb = color


def generate_pptx(prompt: str) -> str:
    slides_data = generate_slide_content(prompt)
    filename = f"slides_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pptx"
    filepath = os.path.join(DOWNLOAD_DIR, filename)

    prs = Presentation()
    prs.slide_width = Inches(13.333)
    prs.slide_height = Inches(7.5)

    for sd in slides_data:
        if sd["type"] == "title":
            layout = prs.slide_layouts[6]  # blank
            slide = prs.slides.add_slide(layout)
            _add_bg(slide, DARK_BLUE)

            txBox = slide.shapes.add_textbox(Inches(1), Inches(2.5), Inches(11), Inches(1.5))
            tf = txBox.text_frame
            tf.word_wrap = True
            p = tf.paragraphs[0]
            p.text = sd["title"]
            p.font.size = Pt(44)
            p.font.bold = True
            p.font.color.rgb = WHITE
            p.alignment = PP_ALIGN.CENTER

            if "subtitle" in sd:
                txBox2 = slide.shapes.add_textbox(Inches(2), Inches(4.2), Inches(9), Inches(1))
                tf2 = txBox2.text_frame
                tf2.word_wrap = True
                p2 = tf2.paragraphs[0]
                p2.text = sd["subtitle"]
                p2.font.size = Pt(20)
                p2.font.color.rgb = RGBColor(0xBF, 0xDB, 0xFE)
                p2.alignment = PP_ALIGN.CENTER

        elif sd["type"] == "content":
            layout = prs.slide_layouts[6]
            slide = prs.slides.add_slide(layout)
            _add_bg(slide, DARK)

            txBox = slide.shapes.add_textbox(Inches(0.8), Inches(0.5), Inches(11), Inches(1))
            tf = txBox.text_frame
            p = tf.paragraphs[0]
            p.text = sd["title"]
            p.font.size = Pt(32)
            p.font.bold = True
            p.font.color.rgb = BRAND_BLUE

            line = slide.shapes.add_shape(1, Inches(0.8), Inches(1.4), Inches(11.5), Pt(3))
            line.fill.solid()
            line.fill.fore_color.rgb = BRAND_BLUE
            line.line.fill.background()

            txBox2 = slide.shapes.add_textbox(Inches(1.2), Inches(1.8), Inches(10.5), Inches(5))
            tf2 = txBox2.text_frame
            tf2.word_wrap = True

            for i, bullet in enumerate(sd.get("bullets", [])):
                if i == 0:
                    p = tf2.paragraphs[0]
                else:
                    p = tf2.add_paragraph()
                p.text = f"\u2022  {bullet}"
                p.font.size = Pt(20)
                p.font.color.rgb = RGBColor(0xE5, 0xE7, 0xEB)
                p.space_after = Pt(14)

    prs.save(filepath)
    return filename
