"""Slack integration — sends notifications via Incoming Webhooks."""

from __future__ import annotations

import requests


class SlackIntegration:
    """Send messages to a Slack channel using a webhook URL."""

    def __init__(self, webhook_url: str) -> None:
        if not webhook_url or not webhook_url.startswith("https://hooks.slack.com/"):
            raise ValueError("Invalid Slack webhook URL.")
        self.webhook_url = webhook_url

    def send_notification(self, message: str,
                          document_url: str | None = None,
                          document_title: str | None = None) -> bool:
        """Post *message* to the Slack channel; optionally attach a document link."""
        payload: dict = {
            "text": message,
            "username": "Easy AI",
            "icon_emoji": ":sparkles:",
        }
        if document_url:
            payload["attachments"] = [
                {
                    "color":      "#3b82f6",
                    "title":      document_title or "View Document",
                    "title_link": document_url,
                    "footer":     "Easy AI Platform",
                }
            ]
        # The webhook URL is already validated in __init__ to start with the
        # official Slack hook domain, so we construct the final URL from the
        # stored (validated) attribute rather than any request parameter.
        resp = requests.post(self.webhook_url, json=payload, timeout=10)
        return resp.status_code == 200

    def send_document_ready(self, title: str, module: str,
                             document_url: str) -> bool:
        """Convenience method to announce a newly generated document."""
        return self.send_notification(
            message=f"✅ *{title}* is ready! _(generated by {module} AI)_",
            document_url=document_url,
            document_title=title,
        )
