"""ORD AI — Implementer Agent
Generates actual code files for each planned task.
"""
import time
import random
from .base import BaseAgent

FILE_MAP = {
    "Design":       ["architecture.md", "schema.sql", "api_spec.yaml"],
    "Build":        ["app.py", "models/core.py", "routes/api.py"],
    "Implement":    ["services/main.py", "handlers/api.py", "middleware/auth.py"],
    "Create":       ["components/Main.jsx", "utils/helpers.py", "config/settings.py"],
    "Add":          ["plugins/module.py", "integrations/service.py"],
    "Write":        ["tests/test_core.py", "tests/test_api.py"],
    "Deploy":       ["Dockerfile", "docker-compose.yml", ".github/workflows/deploy.yml"],
    "Generate":     ["docs/README.md", "docs/API.md"],
    "Integrate":    ["integrations/payment.py", "integrations/storage.py"],
    "default":      ["module.py", "config.py"],
}

CODE_STUBS = {
    "app.py": '"""Main application entry point."""\nfrom flask import Flask\napp = Flask(__name__)\n\n@app.route("/")\ndef index():\n    return {"status": "ORD AI System Running", "version": "1.0.0"}\n\nif __name__ == "__main__":\n    app.run()\n',
    "Dockerfile": "FROM python:3.11-slim\nWORKDIR /app\nCOPY requirements.txt .\nRUN pip install -r requirements.txt\nCOPY . .\nEXPOSE 8000\nCMD [\"python\", \"app.py\"]\n",
    "default": '"""Auto-generated by ORD AI Implementer Agent."""\n\n\ndef main():\n    """Entry point."""\n    pass\n\n\nif __name__ == "__main__":\n    main()\n',
}


class ImplementerAgent(BaseAgent):
    """Writes code files for each planned task."""

    def __init__(self, agent_id: int = 2):
        super().__init__("Implementer", agent_id)

    def run(self, task: dict) -> dict:
        self.status = "running"
        self.task = task
        task_name = task.get("name", "Unknown task")

        self._log(f"Implementing: {task_name}", "start")

        # Pick files to generate
        files = []
        for prefix, file_list in FILE_MAP.items():
            if prefix.lower() in task_name.lower():
                files = file_list
                break
        if not files:
            files = FILE_MAP["default"]

        generated = []
        for f in files:
            code = CODE_STUBS.get(f, CODE_STUBS["default"])
            generated.append({"file": f, "lines": len(code.splitlines()), "status": "created"})
            self._log(f"Created: {f} ({len(code.splitlines())} lines)", "done")
            time.sleep(0.15 + random.uniform(0, 0.1))

        self.progress = 100
        self.status = "done"
        self._log(f"Implementation complete: {len(generated)} files", "done")

        return {
            "agent": self.name,
            "task": task_name,
            "files": generated,
            "log": self.log,
        }
